version: '3'

services:
    postgres:
        image: postgres
        container_name: finance-app-postgres
        environment:
            POSTGRES_PASSWORD: 123
            POSTGRES_USER: postgres
            POSTGRES_DB: finance-app
        ports:
            - '5432:5432'
        volumes:
            - /c/Users/leosu/postgres/finance-app:/var/lib/postgresql/data
